name: script check

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f req.txt ]; then pip install -r requirements.txt; fi
      - name: Build
        run: for f in $(find . -name "*.py"); do python -m py_compile $f; done